#  1. 넘파이(Numpy)
넘파이(Numpy)는 파이썬에서 사용되는 과학 및 수학 연산을 위한 강력한 라이브러리입니다. 주로 다차원 배열을 다루는 데에 특화되어 있어, 데이터 분석, 머신러닝, 과학 계산 등 다양한 분야에서 널리 사용됩니다. 넘파이 배열은 C 언어로 구현되어 있어 연산이 빠르고 효율적입니다. 특히 큰 데이터셋에서 수치 연산을 수행할 때 뛰어난 성능을 보입니다. 또한 메모리 사용을 최적화하고 효율적으로 관리합니다.

In [1]:
pip install numpy

# 2. 넘파이의 주요 특징과 기능


### 2-1 다차원 배열(N-dimensional array)

넘파이의 핵심은 다차원 배열인 ndarray입니다. 이 배열은 동일한 자료형을 가지는 원소들로 이루어져 있습니다. 다차원 배열은 1차원, 2차원, 3차원 등 다양한 차원을 가질 수 있습니다.

In [1]:
import numpy as np
# 리스트
list1 = [1, 2, 3, 4]
list2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(list1)
print(list2)
print(type(list1))
print(type(list1[1]))
print(type(list2))
print(type(list2[1]))

# ndarray
# 1차원 배열
ndarr1 = np.array([1, 2, 3, 4])
print(ndarr1)
print(type(ndarr1)) # ndarray = n dimension array
print(type(ndarr1[1]))
# 2차원 배열
ndarr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(ndarr2)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>
<class 'int'>
<class 'list'>
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int64'>
[[1 2 3]
 [4 5 6]]


### 2-2 리스트와 ndarray 변환

데이터 타입을 다른 데이터 타입으로 변환할 수 있습니다. 리스트에서 배열로의 변환은 np.array() 함수를 사용하고, 배열에서 리스트로의 변환은 tolist() 메서드를 사용합니다.

In [4]:
# 리스트를 ndarray로 변환
list1 = [1, 2, 3, 4]
ndarr1 = np.array(list1)
print(ndarr1)
print(type(ndarr1))

# ndarray를 리스트로 변환
list2 = ndarr1.tolist()
print(list2)
print(type(list2))

[1 2 3 4]
<class 'numpy.ndarray'>
[1, 2, 3, 4]
<class 'list'>


### 2-3 ndarray의 데이터 타입

넘파이의 ndarray는 동일한 자료형을 가지는 원소들로 이루어져 있으며, 다양한 데이터 타입을 지원합니다.

In [5]:
list1 = [1, 3.14, 'Python', '😎', True]
print(list1)
print(list1[3])

ndarr1 = np.array([1, 2, 3, 4])
print(ndarr1)
ndarr2 = np.array([1, 2, 3.14, 4]) # 모든 요소가 float로 변경됨
print(ndarr2)
ndarr3 = np.array([1, 2, 3.14, True]) # 모든 요소가 float로 변경됨
print(ndarr3)
ndarr4 = np.array(['1', 2, 3.14, True]) # 모든 요소가 문자열로 변경됨
print(ndarr4)
print(type(ndarr4))

ndarr3 = np.array([1, 2, 3.14, True], dtype=int) # 모든 요소가 int로 변경됨
print(ndarr3)
ndarr4 = np.array(['1', 2, 3.14, True], dtype=int) # 모든 요소가 int로 변경됨
print(ndarr4)
# ndarr4 = np.array(['1', '2', '3.14', 'True'], dtype=int) # 에러

[1, 3.14, 'Python', '😎', True]
😎
[1 2 3 4]
[1.   2.   3.14 4.  ]
[1.   2.   3.14 1.  ]
['1' '2' '3.14' 'True']
<class 'numpy.ndarray'>
[1 2 3 1]
[1 2 3 1]


### 2-4 ndarray 인덱싱과 슬라이싱

넘파이의 ndarray는 리스트와 유사하게 인덱싱과 슬라이싱을 지원합니다.

In [3]:
ndarr1 = np.array(['🍓','🍉','🍎','🍊','🍌'])
print(ndarr1)
print(ndarr1.shape)

# 인덱싱
print(ndarr1[0])
print(ndarr1[4])
print(ndarr1[-1])
print(ndarr1[-2])

# 슬라이싱
print(ndarr1[0:3])
print(ndarr1[2:])
print(ndarr1[:3])

['🍓' '🍉' '🍎' '🍊' '🍌']
(5,)
🍓
🍌
🍌
🍊
['🍓' '🍉' '🍎']
['🍎' '🍊' '🍌']
['🍓' '🍉' '🍎']


In [4]:
ndarr2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])
print(ndarr2d.shape)

print(ndarr2d[0, 2])
print(ndarr2d[0][2])

# 0행 가져오기
print(ndarr2d[0])
print(ndarr2d[0,])
print(ndarr2d[0,:])

# 0열 가져오기
print(ndarr2d[:, 0])

(3, 4)
3
3
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 5 9]


### 2-5 Fancy Indexing

Fancy indexing은 넘파이에서 배열을 인덱싱하는 강력하고 유연한 방법 중 하나입니다. Fancy indexing은 정수 배열이나 불리언 배열을 사용하여 배열의 일부를 선택하는 방법을 말합니다. 이를 통해 여러 개의 요소를 한 번에 선택하거나 조건에 맞게 선택할 수 있습니다.

In [5]:
ndarr1 = np.array([10, 15, 2, 8, 20, 90, 85, 44, 23, 32])
idx = [2, 5, 9]
print(ndarr1[idx]) # ndarr1[[2, 5, 9]]

ndarr2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])
print(ndarr2d[[0, 1], :])

[ 2 90 32]
[[1 2 3 4]
 [5 6 7 8]]


### 2-6 Boolean Indexing

Boolean Indexing은 넘파이에서 배열의 원소를 선택하는 강력하고 유용한 방법 중 하나입니다. 이 방법은 불리언(Boolean) 값으로 이루어진 배열을 사용하여 조건을 충족하는 원소만 선택하는 방식입니다.

In [2]:
ndarr1 = np.array(['🍓','🍉','🍎','🍊','🍌'])
selValue = [True, False, True, True, False]
print(ndarr1[selValue])

selValue = [True, False, True]
# print(ndarr1[selValue]) # 에러

ndarr2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])
print(ndarr2d > 7)
print(ndarr2d[ndarr2d > 7])

['🍓' '🍎' '🍊']
[[False False False False]
 [False False False  True]
 [ True  True  True  True]]
[ 8  9 10 11 12]


# 3. 행렬 연산
넘파이에서는 다차원 배열인 ndarray를 사용하여 행렬 연산을 수행할 수 있습니다. 행렬 연산은 선형 대수와 관련이 깊어, 데이터 과학, 머신러닝, 통계 등 다양한 분야에서 사용됩니다.

In [5]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4, 5],
              [1, 2, 3]])
print(a.shape, b.shape)

# 행렬 덧셈
print(a + b)

# 행렬 뺄셈
print(a - b)

# 행렬 원소별 곱셈(Element-wise Product)
print(a * b)

# 행렬 곱(Dot Product)
# print(np.dot(a, b))
# print(a @ b)

# 행렬 나눗셈
print(a / b)

# 전치행렬: 행과 열을 바꿈
print(a.T)

# 역행렬
# np.linalg.inv(a) # 역행렬을 구하지 못하면 LinAlgError 에러발생
c = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(c))

(2, 3) (2, 3)
[[4 6 8]
 [3 5 7]]
[[-2 -2 -2]
 [ 1  1  1]]
[[ 3  8 15]
 [ 2  6 12]]
[[0.33333333 0.5        0.6       ]
 [2.         1.5        1.33333333]]
[[1 2]
 [2 3]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


# 4. 순차적인 값 생성
NumPy에서 np.arange() 함수는 일정한 간격으로 숫자들을 생성하는 데 사용됩니다. 이 함수는 Python의 기본 range() 함수와 유사하지만, NumPy 배열을 반환하므로 수학적인 연산이 가능합니다.

In [7]:
# numpy.arange([start, ]stop, [step, ], dtype=None)
arr1 = range(1, 11)
print(arr1)

for i in arr1:
    print(i, end=' ')

arr2 = np.arange(1, 11)
print(arr2)

for i in arr2:
    print(i, end=' ')

range(1, 11)
1 2 3 4 5 6 7 8 9 10 [ 1  2  3  4  5  6  7  8  9 10]
1 2 3 4 5 6 7 8 9 10 

#5. 정렬
NumPy의 np.sort() 함수는 배열을 정렬하는 데 사용됩니다. 이 함수는 기본적으로 원래 배열을 변경하지 않고 정렬된 배열의 복사본을 반환합니다.

In [9]:
ndarr1 = np.array([1, 10, 5, 7, 2, 4, 3, 6, 8, 9])
print(ndarr1)

print(np.sort(ndarr1)) # 오름차순 정렬
print(ndarr1)

# np.sort(ndarr1, reverse=True) # reverse 속성이 없음
print(np.sort(ndarr1)[::-1])

ndarr2d = np.array([[11, 10, 12, 9],
                    [21, 1, 4, 2],
                    [5, 6, 30, 8]])
print(ndarr2d.shape)

# 행 정렬
print(np.sort(ndarr2d, axis=0))
# 열 정렬
print(np.sort(ndarr2d, axis=1))
# 열 정렬 내림차순
print(np.sort(ndarr2d, axis=1)[:,::-1])
# 축의 마지막 방향
print(np.sort(ndarr2d, axis=-1))

[ 1 10  5  7  2  4  3  6  8  9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1 10  5  7  2  4  3  6  8  9]
[10  9  8  7  6  5  4  3  2  1]
(3, 4)
[[ 5  1  4  2]
 [11  6 12  8]
 [21 10 30  9]]
[[ 9 10 11 12]
 [ 1  2  4 21]
 [ 5  6  8 30]]
[[12 11 10  9]
 [21  4  2  1]
 [30  8  6  5]]
[[ 9 10 11 12]
 [ 1  2  4 21]
 [ 5  6  8 30]]
